### ISSUE TITLE
Why enforce a schema on the users collection?

### ISSUE THREAD

**Issue by geekwilson** [copleykj/socialize-user-model#5] opened 2018-02-08 20:11 UTC
Although changes to the user collection are not frequent, when the user collection changes this will need to be updated each time. `emails.$.default` is no longer valid and breaks `Accounts.createUser()`.

**Comment by copleykj** [comment] 2018-02-08 20:41
I don't mind changing this if the accounts package changes. This is more slated towards if fields need to be added to the collection so as to enforce data integrity.

I will look into this issue and see what the issue is and then issue a patch.

**Comment by geekwilson** [comment] 2018-02-08 20:58
I would push for including only the fields used by the socialize suite and not ones that accounts-base are responsible for but thanks for your efforts anyways!

**Comment by copleykj** [comment] 2018-02-08 21:12
The problem with that is you either attach a schema or you don't. There's no in between, so there is no way to include only fields used by socialize packages.

**Comment by copleykj** [comment] 2018-02-09 12:11
Can you give me some more information on this as I'm not able to reproduce this? The stack trace from the error you receive and the output of `meteor list` should be a good start.

**Comment by geekwilson** [comment] 2018-02-09 17:09
I just did a quick repro from scratch, you can see from this user that the `default` field is not created in the email object in the `emails` field:

```
{ "_id" : "5LbMiYb5QR3DhhSKw", "createdAt" : ISODate("2018-02-09T16:54:00.884Z"), "services" : { "password" : { "bcrypt" : "$2a$10$UN6nq3rWjSqw7TAo63vwI.svZ1fcaFt93.16RHJ5ziwBt2qJ5s06S" }, "resume" : { "loginTokens" : [ ] } }, "emails" : [ { "address" : "chatbot@commun-o.com", "verified" : false } ], "profile" : { "name" : "Communo Bot" } }
```

Stack trace
```
I20180209-10:06:07.471(-7)? Exception while invoking method 'createUser' Error: Default is required (emails.0.default) in users insert
I20180209-10:06:07.472(-7)?     at getErrorObject (packages/aldeed:collection2/collection2.js:498:17)
I20180209-10:06:07.472(-7)?     at doValidate (packages/aldeed:collection2/collection2.js:470:13)
I20180209-10:06:07.472(-7)?     at Collection.Mongo.Collection.(anonymous function) [as insert] (packages/aldeed:collection2/collection2.js:195:14)
I20180209-10:06:07.472(-7)?     at AccountsServer.Ap.insertUserDoc (packages/accounts-base/accounts_server.js:1340:25)
I20180209-10:06:07.480(-7)?     at createUser (packages/accounts-password/password_server.js:1054:25)
I20180209-10:06:07.480(-7)?     at packages/accounts-password/password_server.js:1085:20
I20180209-10:06:07.480(-7)?     at tryLoginMethod (packages/accounts-base/accounts_server.js:259:14)
I20180209-10:06:07.480(-7)?     at AccountsServer.Ap._loginMethod (packages/accounts-base/accounts_server.js:393:5)
I20180209-10:06:07.480(-7)?     at MethodInvocation.createUser (packages/accounts-password/password_server.js:1071:19)
I20180209-10:06:07.480(-7)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)
I20180209-10:06:07.480(-7)?     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
I20180209-10:06:07.480(-7)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
I20180209-10:06:07.481(-7)?     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
I20180209-10:06:07.481(-7)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
I20180209-10:06:07.481(-7)?     at Promise (packages/ddp-server/livedata_server.js:715:46)
I20180209-10:06:07.481(-7)?     at new Promise (<anonymous>)
I20180209-10:06:07.481(-7)?     at Session.method (packages/ddp-server/livedata_server.js:689:23)
I20180209-10:06:07.481(-7)?     at packages/ddp-server/livedata_server.js:559:43
I20180209-10:06:07.481(-7)? Sanitized and reported to the client as: Default is required (emails.0.default) in users insert [400]
```

meteor list
```
accounts-password      1.5.0  Password support for accounts
accounts-ui            1.3.0  Simple templates to add login widgets to an app
autopublish            1.0.7  (For prototyping only) Publish the entire database to all clients
blaze-html-templates   1.1.2  Compile HTML templates into reactive UI with Meteor Blaze
ecmascript             0.10.3  Compiler plugin that supports ES2015+ in all .js files
es5-shim               4.7.3  Shims and polyfills to improve ECMAScript 5 support
insecure               1.0.7  (For prototyping only) Allow all database writes from the client
meteor-base            1.3.0  Packages that every Meteor app needs
mobile-experience      1.0.5  Packages for a great mobile user experience
mongo                  1.4.3  Adaptor for using MongoDB and Minimongo over DDP
reactive-var           1.0.11  Reactive variable
shell-server           0.3.1  Server-side component of the `meteor shell` command.
socialize:messaging    1.0.0  A social messaging package
standard-minifier-css  1.4.0  Standard css minifier used with Meteor apps by default.
standard-minifier-js   2.3.1  Standard javascript minifiers used with Meteor apps by default.
tracker                1.1.3  Dependency tracker to allow reactive callbacks
```

**Comment by copleykj** [comment] 2018-02-09 22:15
should be fixed

**Closed as completed** 2018-02-09 22:15 UTC
